name: assess_anime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  collection: ^1.18.0
  shared_preferences: ^2.1.1
  http: ^1.2.1
  get_it: ^7.6.0
  get: ^4.3.4
  cached_network_image: ^3.2.3
  images_picker: ^1.2.11
  connectivity_plus: ^6.0.2
  url_launcher: ^6.1.5
  just_audio_libwinmedia: ^0.0.4
  just_audio: ^0.9.18
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/